// Matches the backend TRADITIONS config.
// Each entry includes display metadata and church info for the About section.
export const TRADITIONS = {
  serbian: {
    label: "Serbian", calendar: "Julian",
    website: "https://www.spc.rs",
    founded: "1219 AD",
    patron: "Saint Sava",
    description: "Granted autocephaly in 1219 by the Ecumenical Patriarchate through Saint Sava, first Serbian Archbishop. Maintains the full Byzantine liturgical tradition on the Julian calendar. Headquartered in Belgrade.",
    logo: "☩",
  },
  russian: {
    label: "Russian", calendar: "Julian",
    website: "https://www.patriarchia.ru",
    founded: "988 AD (Patriarchate 1589)",
    patron: "Equal-to-Apostles Vladimir",
    description: "Christianity came to Rus in 988 under Prince Vladimir. The Moscow Patriarchate received autocephaly in 1448 and was elevated to Patriarchate in 1589. The largest Orthodox church by number of faithful worldwide.",
    logo: "☦",
  },
  greek: {
    label: "Greek", calendar: "Revised",
    website: "https://www.patriarchate.org",
    founded: "36 AD (traditional)",
    patron: "Saint Andrew the Apostle",
    description: "The Ecumenical Patriarchate of Constantinople, senior in honor among Orthodox churches. Founded by Saint Andrew, it remains the spiritual center of Eastern Orthodoxy despite reduced political power after 1453.",
    logo: "☩",
  },
  bulgarian: {
    label: "Bulgarian", calendar: "Revised",
    website: "https://bg-patriarshia.bg",
    founded: "870 AD (Patriarchate 927)",
    patron: "Saints Cyril and Methodius",
    description: "The Bulgarian Patriarchate, established in 927, was the first Slavic Patriarchate. Disciples of Saints Cyril and Methodius created the Cyrillic alphabet here, enabling Christian literacy throughout the Slavic world.",
    logo: "☦",
  },
  romanian: {
    label: "Romanian", calendar: "Revised",
    website: "https://patriarhia.ro",
    founded: "1st century (tradition), Patriarchate 1925",
    patron: "Saint Andrew the Apostle",
    description: "One of the largest Orthodox churches, the Romanian Patriarchate serves approximately 19 million faithful. Its heritage traces to the Apostle Andrew, and it plays a central role in the cultural life of Romania and its diaspora.",
    logo: "☦",
  },
  jerusalem: {
    label: "Jerusalem", calendar: "Julian",
    website: "https://www.jerusalem-patriarchate.info",
    founded: "33 AD (Pentecost)",
    patron: "Saint James the Brother of the Lord",
    description: "The most ancient of all Christian communities, established at Pentecost. The Jerusalem Patriarchate maintains custody of the holiest Christian sites: the Holy Sepulchre, Gethsemane, Bethlehem, and Nazareth.",
    logo: "✚",
  },
  georgian: {
    label: "Georgian", calendar: "Julian",
    website: "https://www.patriarchate.ge",
    founded: "337 AD",
    patron: "Saint Nino, Equal-to-Apostles",
    description: "One of the oldest Christian nations. Saint Nino brought the faith to Georgia circa 327 AD. The Church developed its own unique alphabet for biblical translations and preserved Georgian identity through centuries of invasion.",
    logo: "✠",
  },
  antioch: {
    label: "Antiochian", calendar: "Revised",
    website: "https://antiochpatriarchate.org",
    founded: "37 AD",
    patron: "Saints Peter and Paul",
    description: "Believers were first called 'Christians' in Antioch (Acts 11:26). Founded by Saints Peter and Paul, the Patriarchate of Antioch is one of the ancient Pentarchy and serves communities across the Middle East and diaspora in Arabic.",
    logo: "☩",
  },
  alexandria: {
    label: "Alexandrian", calendar: "Revised",
    website: "https://www.patriarchateofalexandria.com",
    founded: "42 AD",
    patron: "Saint Mark the Evangelist",
    description: "Founded by the Evangelist Mark in 42 AD. The Catechetical School of Alexandria, home to Clement, Origen, and Athanasius, shaped Christian theology for centuries. The Patriarchate serves across the African continent.",
    logo: "☩",
  },
  ethiopian: {
    label: "Ethiopian", calendar: "Julian",
    website: "https://www.ethiopianorthodox.org",
    founded: "340 AD",
    patron: "Saint Frumentius (Abba Selama)",
    description: "One of the oldest Christian churches. Ethiopia received Christianity in 340 AD through Saints Frumentius and Aedesius. The Tewahedo ('unified') Church preserves the Book of Enoch, the Book of Jubilees, and other ancient texts absent from Western canons.",
    logo: "✙",
  },
  oriental: {
    label: "Oriental Orthodox", calendar: "Julian",
    website: "https://www.copticchurch.net",
    founded: "42 AD",
    patron: "Saint Mark the Evangelist",
    description: "The Coptic Orthodox Church of Alexandria, founded by Saint Mark in 42 AD, is the mother church of Oriental Orthodoxy. The Coptic tradition gave monasticism to the world through Saints Anthony and Pachomius.",
    logo: "☩",
  },
  armenian: {
    label: "Armenian Apostolic", calendar: "Julian", note: "Non-Chalcedonian",
    website: "https://www.armenianchurch.us",
    founded: "301 AD",
    patron: "Saint Gregory the Illuminator",
    description: "Armenia was the first nation to adopt Christianity as state religion in 301 AD under King Tiridates III and Saint Gregory the Illuminator. The Armenian Apostolic Church uniquely celebrates Christmas on January 6 (Epiphany) without a separate feast.",
    logo: "✙",
  },
};
