// Matches the backend TRADITIONS config.
// Each entry includes display metadata and church info for the About section.
// Ordering: Eastern Orthodox by canonical diptychs order, then Oriental Orthodox by founding date.
export const TRADITIONS = {
  // ── Eastern Orthodox (Chalcedonian) — canonical diptychs order ─────────────
  greek: {
    label: "Ecumenical Patriarchate", calendar: "Revised",
    website: "https://www.patriarchate.org",
    founded: "c. 36 AD (traditional)",
    patron: "Saint Andrew the Apostle",
    description: "The Ecumenical Patriarchate of Constantinople holds the primacy of honor in the Orthodox Church and serves as its spiritual center. Founded by the Apostle Andrew, it remains the seat of the first hierarch of Orthodoxy despite the Ottoman conquest of 1453.",
    logo: "☩",
  },
  alexandria: {
    label: "Alexandrian", calendar: "Revised",
    website: "https://www.patriarchateofalexandria.com",
    founded: "42 AD",
    patron: "Saint Mark the Evangelist",
    description: "The Greek Orthodox Patriarchate of Alexandria and All Africa, founded by the Evangelist Mark in 42 AD. The Catechetical School of Alexandria — home to Clement, Origen, and Athanasius — shaped Christian theology for centuries. The Patriarchate serves across the African continent.",
    logo: "☩",
  },
  antioch: {
    label: "Antiochian", calendar: "Revised",
    website: "https://antiochpatriarchate.org",
    founded: "37 AD",
    patron: "Saints Peter and Paul",
    description: "The Greek Orthodox Patriarchate of Antioch and All the East — where believers were first called Christians (Acts 11:26). Founded by Saints Peter and Paul, it is one of the ancient Pentarchy and today serves communities across the Middle East and its diaspora, with liturgy in Arabic.",
    logo: "☩",
  },
  jerusalem: {
    label: "Jerusalem", calendar: "Julian",
    website: "https://www.jerusalem-patriarchate.info",
    founded: "33 AD (Pentecost)",
    patron: "Saint James the Brother of the Lord",
    description: "The Greek Orthodox Patriarchate of Jerusalem — the most ancient of all Christian communities, established at Pentecost in 33 AD. Custodian of the holiest Christian sites: the Church of the Holy Sepulchre, the Garden of Gethsemane, Bethlehem, and Nazareth.",
    logo: "✚",
  },
  russian: {
    label: "Russian", calendar: "Julian",
    website: "https://www.patriarchia.ru",
    founded: "988 AD (Patriarchate 1589)",
    patron: "Equal-to-Apostles Vladimir",
    description: "The Russian Orthodox Church (Moscow Patriarchate). Christianity came to Rus in 988 under Prince Vladimir. The Moscow Patriarchate received autocephaly in 1448 and was elevated to Patriarchate in 1589. The largest Orthodox church by number of faithful worldwide.",
    logo: "☦",
  },
  georgian: {
    label: "Georgian", calendar: "Julian",
    website: "https://www.patriarchate.ge",
    founded: "337 AD",
    patron: "Saint Nino, Equal-to-Apostles",
    description: "The Apostolic Autocephalous Orthodox Church of Georgia — one of the world's oldest Christian nations. Saint Nino brought the faith to Georgia circa 327 AD. The Church developed its own unique script for biblical translation and preserved Georgian identity through centuries of invasion.",
    logo: "✠",
  },
  serbian: {
    label: "Serbian", calendar: "Julian",
    website: "https://www.spc.rs",
    founded: "1219 AD",
    patron: "Saint Sava",
    description: "The Serbian Orthodox Church, granted autocephaly in 1219 by the Ecumenical Patriarchate through Saint Sava, first Serbian Archbishop. Maintains the full Byzantine liturgical tradition on the Julian calendar. Headquartered in Belgrade.",
    logo: "☩",
  },
  romanian: {
    label: "Romanian", calendar: "Revised",
    website: "https://patriarhia.ro",
    founded: "1st century (tradition), Patriarchate 1925",
    patron: "Saint Andrew the Apostle",
    description: "The Romanian Orthodox Church, one of the largest Orthodox churches with approximately 19 million faithful. Its apostolic heritage traces to Saint Andrew who preached in Scythia Minor (today's Dobrogea). The Patriarchate plays a central role in the cultural life of Romania and its diaspora.",
    logo: "☦",
  },
  bulgarian: {
    label: "Bulgarian", calendar: "Revised",
    website: "https://bg-patriarshia.bg",
    founded: "870 AD (Patriarchate 927)",
    patron: "Saints Cyril and Methodius",
    description: "The Bulgarian Orthodox Church (Bulgarian Patriarchate), established in 927, was the first Slavic Patriarchate. Disciples of Saints Cyril and Methodius created the Glagolitic and later Cyrillic alphabet here, enabling Christian literacy throughout the Slavic world.",
    logo: "☦",
  },
  // ── Oriental Orthodox (Non-Chalcedonian) — by founding date ────────────────
  oriental: {
    label: "Coptic", calendar: "Julian", note: "Non-Chalcedonian",
    website: "https://www.copticchurch.net",
    founded: "42 AD",
    patron: "Saint Mark the Evangelist",
    description: "The Coptic Orthodox Church of Alexandria, founded by Saint Mark the Evangelist in 42 AD. Separated from Chalcedonian communion in 451 AD on Christological grounds, the Coptic Church preserves an unbroken apostolic tradition and gave monasticism to the world through Saints Anthony and Pachomius.",
    logo: "☩",
  },
  armenian: {
    label: "Armenian Apostolic", calendar: "Julian", note: "Non-Chalcedonian",
    website: "https://www.armenianchurch.us",
    founded: "301 AD",
    patron: "Saint Gregory the Illuminator",
    description: "The Armenian Apostolic Church — Armenia was the first nation to adopt Christianity as state religion in 301 AD under King Tiridates III and Saint Gregory the Illuminator. The Church uniquely celebrates the Nativity on January 6 (Epiphany) without a separate December feast.",
    logo: "✙",
  },
  ethiopian: {
    label: "Ethiopian", calendar: "Julian", note: "Non-Chalcedonian",
    website: "https://www.ethiopianorthodox.org",
    founded: "340 AD",
    patron: "Saint Frumentius (Abba Selama)",
    description: "The Ethiopian Orthodox Tewahedo Church — one of the oldest Christian churches. Ethiopia received Christianity circa 340 AD through Saints Frumentius and Aedesius. The Tewahedo ('unified') Church preserves the Book of Enoch, the Book of Jubilees, and other ancient texts absent from Western canons.",
    logo: "✙",
  },
};
